policy:
  path: null
  input_dims: 58
  output_dims: 24

  obs_normalization: true
  init_joint_config:
    FL_hip_joint: 0.1
    RL_hip_joint: 0.1
    FR_hip_joint: -0.1
    RR_hip_joint: -0.1

    FL_thigh_joint: 0.8
    RL_thigh_joint: 1.0
    FR_thigh_joint: 0.8
    RR_thigh_joint: 1.0

    FL_calf_joint: -1.5
    RL_calf_joint: -1.5
    FR_calf_joint: -1.5
    RR_calf_joint: -1.5
  
  leg_joint_bound: [0.15, 0.4, 0.4] 
 